<?php

    namespace ServiceBundle\Repository;

    use Doctrine\ORM\EntityRepository;

    /**
     * ActionsRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class ActionRepository extends EntityRepository {

        public function getActionsTotal($actions) {
            $sum = 0;
            foreach ($actions as $action) {
                $sum += $action->getPrice();
            }
            return $sum;
        }

    }
    