<?php

namespace ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MotorcycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorcycleRepository extends EntityRepository
{
                public function getCustomerMotorcyclesRegPlateID($customerId) {
          
            $motorcycles = $this->findByUserId($customerId);
            $choices = [];
            foreach ($motorcycles as $motorcycle) {
                $choices[] = [$motorcycle->getRegPlate() => $motorcycle->getId()];
            }
            return $motorcycles;
        }
        
          public function getCustomerMotorcycles($userId) {

            $repository = $this->getDoctrine()->getRepository('ServiceBundle:Motorcycle');
            $motorcycles = $repository->findByUserId($userId);

            return $motorcycles;
        }
}
