<?php

namespace ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MotorcycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorcycleRepository extends EntityRepository
{
}
