<?php

    namespace ServiceBundle\Repository;

    use Doctrine\ORM\EntityRepository;

    /**
     * OrderStatusRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class OrderStatusRepository extends EntityRepository {

        public function chooseStatusForAddOrder() {

            $choices = [];
            for ($i = 1; $i < 4; $i++) {
                $choices[] = $this->findOneById($i);
            }
            return $choices;
        }

    }
    