<?php

    namespace ServiceBundle\Repository;

    use Doctrine\ORM\EntityRepository;

    /**
     * PartsRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class ServiceOrderRepository extends EntityRepository {

    }
    