security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_MECHANIC:    ROLE_MECHANIC
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
           id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/mechanic/, role: ROLE_MECHANIC }
        - { path: ^/manager/, role: ROLE_MANAGER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        
        
