# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: ServiceBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: service_user_registration }